move CONFIG_PORT to the correct position

diff --git a/scripts/start_installimage b/scripts/start_installimage
--- a/scripts/start_installimage
+++ b/scripts/start_installimage
@@ -23,7 +23,12 @@ set -e -u
 #mac="$(ifdata -ph eth0 | awk '{gsub(":",""); print tolower($1)}')"
 mac=$(awk 'BEGIN {FS="="; RS=" ";} { if ($1 ~ /BOOTIF/) {gsub(/^[^-]+-/, "", $2); gsub(/-/, ":", $2); print tolower($2)}}' /proc/cmdline)
 
-url="${CONFIG_PROTO}:${CONFIG_PORT}//${CONFIG_SERVER}/${CONFIG_PATH}/${mac}/${CONFIG_FILE}"
+if [ -n "$CONFIG_PROTO" ] && [ -n "$CONFIG_PORT" ] && [ -n "$CONFIG_SERVER" ] && [ -n "$CONFIG_PATH" ] && [ -n "$mac" ] && [ -n "$CONFIG_FILE" ]; then
+  url="${CONFIG_PROTO}//${CONFIG_SERVER}:${CONFIG_PORT}/${CONFIG_PATH}/${mac}/${CONFIG_FILE}"
+else
+  echo "One of the needed config options is missing"
+  exit 1
+fi
 
 wget "${url}" --retry-connrefused -q -O /root/config.cfg
 if [ $? != 0 ]; then
